[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
ignored_warnings_from = ["node_modules/@pythnetwork/pyth-sdk-solidity/"]
ignored_error_codes = ["unused-var"]
gas_reports = ["OptionsFactory", "CallOption", "PutOption", "OfferFactory", "Offer"]